[package]
name = "blinmaker-cli"
version = "2.1.0"
authors = ["dragonhaze"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
blinmaker = {git="https://github.com/ilchub/blinmaker2.git"}
